version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:q96LTJv+3i7IdS+aukWDjT8ofp70UreRuTXb4h7asB0=
